MODULE snowydove
DESCRIPTION snowy dove extra module
VERSION 0.1
SOURCE deserts jtsung
BUILD_DATE Jun 16 2020
PROCEDURE SD_NV2TF 1 1
PROCEDURE SD_RADCAL 4 4
PROCEDURE SD_NDVI 2 2
PROCEDURE SD_SHOWPIC 0 0
